# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6c235da3be3d8905fb95ce790268246ae46bfcb786bc598e6d7f3c4a70f5894d1ff0e73bc3680ae64ef0bffefa4acdf8836eef80275420ee57c8d195a47b98f

test:
  secret_key_base: 3baf329b3ad252f591106add60bba2436c72790be9038423695df516c189b2603c9fb186df639812261d5ea5ab5fcdf48ed389a9d257d96e6e7de50f03e21366

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
